### ISSUE TITLE
`get`ing a map doesn't evaluate lazys

### ISSUE THREAD

**Issue by jamosonic** [asimov/asimov-core#15]
If you `get` a map that has `lazy` children they're not evaluated.

``` scss
@each $name, $value in get("colors") {
   color: $value; // error because $value is the lazy object no the value.
}
```
